/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChangesRouteImport } from './routes/changes'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as ReadGoldenDemoRouteImport } from './routes/read.golden-demo'
import { Route as ReadGoldenDemoIdRouteImport } from './routes/read.golden-demo.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesRoute = ChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadGoldenDemoRoute = ReadGoldenDemoRouteImport.update({
  id: '/read/golden-demo',
  path: '/read/golden-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadGoldenDemoIdRoute = ReadGoldenDemoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReadGoldenDemoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changes': typeof ChangesRoute
  '/sources': typeof SourcesRoute
  '/read/golden-demo': typeof ReadGoldenDemoRouteWithChildren
  '/read/golden-demo/$id': typeof ReadGoldenDemoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changes': typeof ChangesRoute
  '/sources': typeof SourcesRoute
  '/read/golden-demo': typeof ReadGoldenDemoRouteWithChildren
  '/read/golden-demo/$id': typeof ReadGoldenDemoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changes': typeof ChangesRoute
  '/sources': typeof SourcesRoute
  '/read/golden-demo': typeof ReadGoldenDemoRouteWithChildren
  '/read/golden-demo/$id': typeof ReadGoldenDemoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changes'
    | '/sources'
    | '/read/golden-demo'
    | '/read/golden-demo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changes'
    | '/sources'
    | '/read/golden-demo'
    | '/read/golden-demo/$id'
  id:
    | '__root__'
    | '/'
    | '/changes'
    | '/sources'
    | '/read/golden-demo'
    | '/read/golden-demo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangesRoute: typeof ChangesRoute
  SourcesRoute: typeof SourcesRoute
  ReadGoldenDemoRoute: typeof ReadGoldenDemoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes': {
      id: '/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof ChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/golden-demo': {
      id: '/read/golden-demo'
      path: '/read/golden-demo'
      fullPath: '/read/golden-demo'
      preLoaderRoute: typeof ReadGoldenDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/golden-demo/$id': {
      id: '/read/golden-demo/$id'
      path: '/$id'
      fullPath: '/read/golden-demo/$id'
      preLoaderRoute: typeof ReadGoldenDemoIdRouteImport
      parentRoute: typeof ReadGoldenDemoRoute
    }
  }
}

interface ReadGoldenDemoRouteChildren {
  ReadGoldenDemoIdRoute: typeof ReadGoldenDemoIdRoute
}

const ReadGoldenDemoRouteChildren: ReadGoldenDemoRouteChildren = {
  ReadGoldenDemoIdRoute: ReadGoldenDemoIdRoute,
}

const ReadGoldenDemoRouteWithChildren = ReadGoldenDemoRoute._addFileChildren(
  ReadGoldenDemoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangesRoute: ChangesRoute,
  SourcesRoute: SourcesRoute,
  ReadGoldenDemoRoute: ReadGoldenDemoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
